bring back the npm package-lock.json to fix the build issue (#62)
#### Objective
In this PR I tried to fix the compiling issue in current CI. And for the Github CI it is hard to use yarn, so I also am trying to bring back the package-lock.json.

#### Abstract
It looks like because the yarn.lock doesn't take effect, so it gets a newer version for the following library:
```
vscode-languageserver-protocol
vscode-languageserver-types
```
So it complains the following building error:
```
node_modules/vscode-languageclient/lib/client.d.ts:2:19 - error TS2305: Module '"../../vscode-languageserver-protocol/lib/common/api"' has no exported member 'RPCMessageType'.

2 import { Message, RPCMessageType, ResponseError, RequestType, RequestType0, RequestHandler, RequestHandler0, GenericRequestHandler, NotificationType, NotificationType0, NotificationHandler, NotificationHandler0, GenericNotificationHandler, MessageReader, MessageWriter, Trace, Event, ClientCapabilities, TextDocumentRegistrationOptions, InitializeParams, InitializeResult, InitializeError, ServerCapabilities, DocumentSelector } from 'vscode-languageserver-protocol';
                    ~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:365:33 - error TS2314: Generic type 'RequestType0<R, E>' requires 2 type argument(s).

365     sendRequest<R, E, RO>(type: RequestType0<R, E, RO>, token?: CancellationToken): Thenable<R>;

extension/src/project/findReplace/searchTree.ts:218:34 - error TS2339: Property 'label' does not exist on type 'string | TreeItemLabel'.
  Property 'label' does not exist on type 'string'.

218                 return itemlebel.label;
                                     ~~~~~

extension/src/project/projectTree.ts:166:17 - error TS2322: Type 'string | TreeItemLabel' is not assignable to type 'string'.
  Type 'TreeItemLabel' is not assignable to type 'string'.

166                 title: treeNode.label,
                    ~~~~~

  node_modules/@types/vscode/index.d.ts:34:9
    34         title: string;
               ~~~~~
    The expected type comes from property 'title' which is declared here on type 'Command'
```

To fix the issue I adopt the following way:
1. bring back the package-lock.json and remove the yarn.lock file
2. change some codes for `TreeItemLabel`

#### Tests Performed
 - run npm run compile or gulp build to very the build
 
#### Screen Shot
Not applicable for this PR